/**
 * @name RobloxShareLeaderboard
 * @author ChatGPT
 * @description Webhook-only Roblox private-server leaderboard scanner for C0LD egg-chat. No CSV/XLSX exports.
 * @version 0.1.0
 */

const PLUGIN_NAME = "RobloxShareLeaderboard";
const SETTINGS_KEY = "settings";
const STATE_KEY = "webhookState";
const DISCORD_EPOCH = 1420070400000n;
const DEFAULT_SETTINGS = {
    webhookUrl: "",
    threadId: "1504955979597349166",
    serverLogsChannelId: "1489879731569426485",
    eggChatChannelId: "1515759898565148884",
    sapphireBotUserId: "1489881332241666139",
    startLocal: "2026-06-13T10:00",
    endLocal: "2026-06-19T10:00",
    autoUpdate: true,
    intervalMinutes: 15,
    maxPages: 800,
    pageLimit: 100,
    logScanGraceDays: 7,
    contentLimit: 1950
};
const SHARE_PATTERNS = [
    /https?:\/\/(?:www\.)?roblox\.com\/share\?code=[^\s<>)]+/i,
    /https?:\/\/(?:www\.)?roblox\.com\/(?:[a-z]{2}(?:-[a-z]{2})?\/)?games\/8737899170\/Pet-Simulator-99\?privateServerLinkCode=[^\s<>)]+/i,
    /(?:^|\s)(\/(?:[a-z]{2}(?:-[a-z]{2})?\/)?games\/8737899170\/Pet-Simulator-99\?privateServerLinkCode=[^\s<>)]+)/i
];
function clean(v){return String(v||"").replace(/[\u200B-\u200D\u2060\uFEFF]/g,"").replace(/\u00a0/g," ").replace(/\r\n?/g,"\n");}
function norm(v){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function sfTime(id){try{return id?Number((BigInt(String(id))>>22n)+DISCORD_EPOCH):0;}catch(_){return 0;}}
function timeSf(ms){try{return String((BigInt(Math.max(0,Number(ms)||0))-DISCORD_EPOCH)<<22n);}catch(_){return "";}}
function msgTime(m){const t=m?.timestamp||m?.editedTimestamp||m?.edited_timestamp;if(t instanceof Date)return t.getTime();if(typeof t==="number")return t;const p=t?Date.parse(String(t)):NaN;return Number.isFinite(p)?p:sfTime(m?.id);}
function dur(ms){const mins=Math.max(0,Math.floor((Number(ms)||0)/60000)),d=Math.floor(mins/1440),h=Math.floor((mins%1440)/60),m=mins%60,a=[];if(d)a.push(`${d}d`);if(h)a.push(`${h}h`);if(m||!a.length)a.push(`${m}m`);return a.join(" ");}
function copy(s){return Object.assign({},DEFAULT_SETTINGS,s||{});}
function el(t,c,x){const n=document.createElement(t);if(c)n.className=c;if(x!==undefined&&x!==null)n.textContent=String(x);return n;}

module.exports = class RobloxShareLeaderboard {
    constructor(){this.settings=copy();this.timer=null;this.running=false;this.modules={};}
    start(){this.settings=copy(BdApi.Data.load(PLUGIN_NAME,SETTINGS_KEY));this.resolveModules();this.restartTimer();BdApi.UI?.showToast?.(`${PLUGIN_NAME} loaded`,{type:"info"});}
    stop(){clearInterval(this.timer);this.timer=null;}
    resolveModules(){try{this.modules.Auth=BdApi.Webpack.getByKeys?.("getToken",{searchExports:true})||null;}catch(_){this.modules.Auth=null;}}
    getSettingsPanel(){
        const root=el("div");root.style.cssText="display:flex;flex-direction:column;gap:10px;padding:12px;max-width:760px";
        root.append(el("div",null,"Webhook-only scanner. Paste the webhook URL here locally; it is saved in BetterDiscord data and is not hard-coded in the repo."));
        for(const [k,label,type] of [["webhookUrl","Discord webhook URL","password"],["threadId","Webhook thread ID","text"],["serverLogsChannelId","Server logs channel ID","text"],["eggChatChannelId","Egg chat channel ID","text"],["sapphireBotUserId","Sapphire bot user ID","text"],["startLocal","Event start","datetime-local"],["endLocal","Event end","datetime-local"],["intervalMinutes","Interval minutes","number"],["maxPages","Max pages","number"],["logScanGraceDays","Deleted-log grace days","number"]])root.append(this.input(k,label,type));
        const auto=el("label");auto.style.cssText="display:flex;gap:8px;align-items:center";const cb=document.createElement("input");cb.type="checkbox";cb.checked=!!this.settings.autoUpdate;cb.onchange=()=>{this.settings.autoUpdate=cb.checked;this.save();this.restartTimer();};auto.append(cb,el("span",null,"Auto-update webhook"));root.append(auto);
        const buttons=el("div");buttons.style.cssText="display:flex;gap:8px";const run=el("button",null,"Run scan + update webhook now");run.type="button";run.onclick=()=>this.runManual();const forget=el("button",null,"Forget webhook message ID");forget.type="button";forget.onclick=()=>{BdApi.Data.save(PLUGIN_NAME,STATE_KEY,{});BdApi.UI?.showToast?.("Webhook message ID cleared",{type:"success"});};buttons.append(run,forget);root.append(buttons);return root;
    }
    input(k,label,type){const wrap=el("label");wrap.style.cssText="display:grid;gap:4px";const i=document.createElement("input");i.type=type;i.value=this.settings[k]??"";i.style.cssText="padding:8px;border-radius:6px;border:1px solid var(--background-modifier-accent);background:var(--input-background);color:var(--text-normal)";i.onchange=()=>{const num=["intervalMinutes","maxPages","logScanGraceDays"].includes(k);this.settings[k]=num?Math.max(1,Number(i.value)||DEFAULT_SETTINGS[k]):i.value.trim();i.value=String(this.settings[k]);this.save();this.restartTimer();};wrap.append(el("b",null,label),i);return wrap;}
    save(){BdApi.Data.save(PLUGIN_NAME,SETTINGS_KEY,this.settings);}
    restartTimer(){clearInterval(this.timer);this.timer=null;if(!this.settings.autoUpdate)return;this.timer=setInterval(()=>this.runScheduled("interval"),Math.max(1,Number(this.settings.intervalMinutes)||15)*60000);setTimeout(()=>this.runScheduled("startup"),30000);}
    async runManual(){try{BdApi.UI?.showToast?.("Scanning Roblox links...",{type:"info"});const r=await this.runScheduled("manual");BdApi.UI?.showToast?.(`Leaderboard updated: ${r.totalMatches} posts, ${r.summary.length} members`,{type:"success"});console.log(`${PLUGIN_NAME} result`,r);}catch(e){console.error(e);BdApi.UI?.showToast?.(`Scan failed: ${e?.message||e}`,{type:"error",timeout:8000});}}
    async runScheduled(reason){if(this.running)return null;this.running=true;try{const r=await this.scan();BdApi.Data.save(PLUGIN_NAME,"lastScan",r);await this.updateWebhook(r);return r;}catch(e){this.saveState(Object.assign({},this.loadState(),{lastError:e?.message||String(e),lastErrorAt:new Date().toISOString(),reason}));if(reason==="manual")throw e;console.error(`${PLUGIN_NAME} update failed`,e);return null;}finally{this.running=false;}}
    window(){const s=Date.parse(this.settings.startLocal),e=Date.parse(this.settings.endLocal);if(!Number.isFinite(s)||!Number.isFinite(e)||e<=s)throw new Error("Invalid event date window");return {startMs:s,endMs:e};}
    async scan(){
        const {startMs,endMs}=this.window(),now=Date.now(),activeUntil=Math.min(now,endMs),logEnd=Math.min(now,endMs+(Math.max(0,Number(this.settings.logScanGraceDays)||0)*86400000));
        const diag={livePages:0,liveMessages:0,liveMatches:0,logPages:0,logMessages:0,logMatches:0,rejected:{},dedupedAway:0};
        const live=await this.scanLive(startMs,activeUntil,diag),logs=await this.scanLogs(startMs,logEnd,diag),evidence=this.dedupe(logs,live,diag),summary=this.summarize(evidence);
        return {generatedAt:new Date().toISOString(),start:new Date(startMs).toISOString(),end:new Date(endMs).toISOString(),serverLogsChannelId:this.settings.serverLogsChannelId,sourceChannelId:this.settings.eggChatChannelId,totalMatches:evidence.length,summary,diagnostics:diag,evidenceMatches:evidence,deletedMatches:logs,liveMatches:live};
    }
    async scanLive(startMs,endMs,diag){const out=[];let before=timeSf(endMs+1),done=false;for(let p=0;p<Number(this.settings.maxPages)&&!done;p++){const ms=await this.page(this.settings.eggChatChannelId,before);diag.livePages++;diag.liveMessages+=ms.length;if(!ms.length)break;for(const m of ms){const t=msgTime(m);if(t&&t<startMs){done=true;continue;}if(!t||t>endMs||t<startMs)continue;const hit=this.liveMatch(m,t,endMs);if(hit){out.push(hit);diag.liveMatches++;}}before=ms[ms.length-1]?.id||"";if(!before)break;if(!done)await sleep(175);}return out;}
    async scanLogs(startMs,endMs,diag){const out=[];let before=timeSf(endMs+1),done=false;for(let p=0;p<Number(this.settings.maxPages)&&!done;p++){const ms=await this.page(this.settings.serverLogsChannelId,before);diag.logPages++;diag.logMessages+=ms.length;if(!ms.length)break;for(const m of ms){const t=msgTime(m);if(t&&t<startMs){done=true;continue;}if(!t||t>endMs||t<startMs)continue;const hit=this.logMatch(m,t,startMs,diag);if(hit){out.push(hit);diag.logMatches++;}}before=ms[ms.length-1]?.id||"";if(!before)break;if(!done)await sleep(175);}return out;}
    reject(diag,k){diag.rejected[k]=(diag.rejected[k]||0)+1;}
    logMatch(m,logTs,startMs,diag){
        const text=this.flatten(m);if(this.authorId(m)!==String(this.settings.sapphireBotUserId)){this.reject(diag,"not_sapphire");return null;}if(!/message\s+deleted/i.test(text)){this.reject(diag,"not_deleted_log");return null;}
        const ch=this.fields(m,"Channel",text);if(!this.isEgg(text,ch)){this.reject(diag,"not_egg_chat");return null;}const msg=this.shareText(this.fields(m,"Message",text),text);if(!msg){this.reject(diag,"no_link_in_message_block");return null;}
        const sourceId=this.sourceMessageId(m,text),sourceTs=sourceId?sfTime(sourceId):logTs,endTs=Date.parse(this.settings.endLocal);if(!sourceTs||sourceTs<startMs||sourceTs>endTs){this.reject(diag,"source_outside_window");return null;}
        const author=this.firstField(m,["Message author","Message Author","Author","User"],text)||this.mention(text)||"Unknown author",guild=this.guildId()||"@me";
        return {source:"server-log",author,authorKey:this.authorKey(author),sourceMessageId:sourceId,canonicalLink:this.link(msg),logMessageId:m.id,timestamp:new Date(sourceTs).toISOString(),deletedLogTimestamp:new Date(logTs).toISOString(),messageUrl:`https://discord.com/channels/${guild}/${this.settings.serverLogsChannelId}/${m.id}`,message:msg};
    }
    liveMatch(m,t,activeUntil){const text=this.flatten(m),msg=this.shareText([],text);if(!msg)return null;const a=this.authorCtx(m),guild=this.guildId()||"@me",activeMs=Math.max(0,activeUntil-t);return {source:"egg-chat-live",author:a.line||"Unknown author",authorKey:a.key||this.authorKey(a.line),sourceMessageId:m.id,canonicalLink:this.link(msg),liveMessageId:m.id,timestamp:new Date(t).toISOString(),activeMs,activeDuration:dur(activeMs),messageUrl:`https://discord.com/channels/${guild}/${this.settings.eggChatChannelId}/${m.id}`,message:msg};}
    dedupe(logs,live,diag){const map=new Map();for(const x of live)map.set(this.evidenceKey(x),x);for(const x of logs)map.set(this.evidenceKey(x),x);const out=Array.from(map.values()).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));diag.dedupedAway=logs.length+live.length-out.length;return out;}
    evidenceKey(x){return x?.sourceMessageId?`message:${x.sourceMessageId}`:[x?.authorKey||"unknown",x?.canonicalLink||"",Math.floor(Date.parse(x?.timestamp||0)/60000)].join("|");}
    summarize(rows){const by=new Map();for(const x of rows){const r=by.get(x.authorKey)||{authorKey:x.authorKey,author:x.author,count:0,eggChatLiveCount:0,totalCount:0,liveActiveMs:0,liveActiveTime:"",logMessageIds:[],eggChatLiveMessageIds:[],sourceMessageIds:[],firstTimestamp:x.timestamp,lastTimestamp:x.timestamp};if(!r.author||r.author==="Unknown author")r.author=x.author;if(x.timestamp<r.firstTimestamp)r.firstTimestamp=x.timestamp;if(x.timestamp>r.lastTimestamp)r.lastTimestamp=x.timestamp;if(x.source==="egg-chat-live"){r.eggChatLiveCount++;if(x.liveMessageId)r.eggChatLiveMessageIds.push(x.liveMessageId);r.liveActiveMs+=Number(x.activeMs)||0;}else{r.count++;if(x.logMessageId)r.logMessageIds.push(x.logMessageId);}if(x.sourceMessageId)r.sourceMessageIds.push(x.sourceMessageId);by.set(x.authorKey,r);}for(const r of by.values()){r.logMessageIds=[...new Set(r.logMessageIds.filter(Boolean))];r.eggChatLiveMessageIds=[...new Set(r.eggChatLiveMessageIds.filter(Boolean))];r.sourceMessageIds=[...new Set(r.sourceMessageIds.filter(Boolean))];r.totalCount=r.count+r.eggChatLiveCount;r.liveActiveTime=dur(r.liveActiveMs);}return [...by.values()].sort((a,b)=>b.totalCount-a.totalCount||b.count-a.count||String(a.author).localeCompare(String(b.author)));}
    async page(channelId,before){const limit=Math.max(1,Math.min(100,Number(this.settings.pageLimit)||100)),data=await this.discord(`/channels/${channelId}/messages?limit=${limit}${before?`&before=${before}`:""}`);return Array.isArray(data)?data:[];}
    token(){for(const c of [this.modules.Auth,this.modules.Auth?.default,this.modules.Auth?.Z,this.modules.Auth?.ZP]){try{const t=c?.getToken?.();if(typeof t==="string"&&t.length>20)return t;}catch(_){}}return "";}
    async discord(endpoint){const token=this.token();if(!token)throw new Error("Could not read Discord token from BetterDiscord Auth module");const res=await this.fetch(`https://discord.com/api/v9${endpoint}`,{headers:{Authorization:token}}),data=await this.read(res),status=res?.status||res?.statusCode||0,ok=res?.ok??(!status||(status>=200&&status<300));if(!ok||data?.code&&data?.message)throw new Error(`Discord API failed: ${status||"unknown"} ${data?.message||""}`.trim());return data;}
    async updateWebhook(result){if(!this.settings.webhookUrl)throw new Error("Set webhook URL in plugin settings");const payload={content:this.webhookText(result),allowed_mentions:{parse:[]}},state=this.loadState();let msg=null;if(state.messageId){try{msg=await this.webhook(this.webhookMessageUrl(state.messageId),"PATCH",payload);}catch(e){if(e?.status!==404&&!/Unknown Message/i.test(e?.message||""))throw e;state.messageId="";}}if(!msg)msg=await this.webhook(this.webhookCreateUrl(),"POST",payload);this.saveState(Object.assign({},state,{messageId:msg?.id||state.messageId||"",threadId:this.settings.threadId||"",lastUpdatedAt:new Date().toISOString(),lastTotalMatches:result.totalMatches,lastAuthorCount:result.summary.length,lastError:""}));}
    webhookCreateUrl(){const base=this.settings.webhookUrl.replace(/\/+$/,"");const p=new URLSearchParams({wait:"true"});if(this.settings.threadId)p.set("thread_id",this.settings.threadId);return `${base}?${p}`;}
    webhookMessageUrl(id){const base=this.settings.webhookUrl.replace(/\/+$/,"");const p=new URLSearchParams();if(this.settings.threadId)p.set("thread_id",this.settings.threadId);return `${base}/messages/${encodeURIComponent(id)}${p.toString()?`?${p}`:""}`;}
    async webhook(url,method,payload){const res=await this.fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),data=await this.read(res),status=res?.status||res?.statusCode||0,ok=res?.ok??(!status||(status>=200&&status<300));if(!ok||data?.code&&data?.message){const e=new Error(`Webhook ${method} failed: ${status||"unknown"} ${data?.message||""}`.trim());e.status=status;throw e;}return data||{};}
    webhookText(r){const now=Math.floor(Date.now()/1000),s=Math.floor(Date.parse(r.start)/1000),e=Math.floor(Date.parse(r.end)/1000),lines=["**C0LD Egg Server Leaderboard**",`_Window <t:${s}:f> to <t:${e}:f> • Updated <t:${now}:R>_`,`_Counted ${r.totalMatches} unique private-server posts across ${r.summary.length} members._`,"","```text",`${"rank".padEnd(5)} ${"author".padEnd(46)} total  del  live`],footer=["```"];for(let i=0;i<r.summary.length;i++){const row=r.summary[i],line=`${String(i+1).padEnd(5)} ${this.cell(row.author||row.authorKey||"Unknown",46).padEnd(46)} ${String(row.totalCount||0).padEnd(5)} ${String(row.count||0).padEnd(4)} ${String(row.eggChatLiveCount||0)}`;if(lines.concat(line,footer).join("\n").length>Number(this.settings.contentLimit||1950))break;lines.push(line);}if(lines.length===6)lines.push(`${"-".padEnd(5)} ${"No matching posts yet".padEnd(46)} 0      0    0`);lines.push(...footer);return lines.join("\n");}
    cell(v,n){const t=clean(v).replace(/\s+/g," ").replace(/`/g,"'").trim();return t.length<=n?t:`${t.slice(0,n-3)}...`;}
    loadState(){try{return BdApi.Data.load(PLUGIN_NAME,STATE_KEY)||{};}catch(_){return {};}}
    saveState(s){BdApi.Data.save(PLUGIN_NAME,STATE_KEY,s||{});}
    async fetch(url,opt){if(typeof BdApi?.Net?.fetch==="function")return BdApi.Net.fetch(url,opt);if(typeof fetch==="function")return fetch(url,opt);throw new Error("No fetch available");}
    async read(res){if(!res)return null;for(const k of ["body","data","rawBody"]){if(res[k]!==undefined&&res[k]!=="")return this.parse(res[k]);}if(typeof res.json==="function"){try{return this.parse(await res.json());}catch(_){}}if(typeof res.text==="function"){try{return this.parse(await res.text());}catch(_){}}return this.parse(res);}
    parse(v){if(typeof v==="string"){try{return v?JSON.parse(v):null;}catch(_){return v;}}return v;}
    authorId(m){const a=this.val(m,["author"]);if(typeof a==="string"&&/^\d{14,24}$/.test(a))return a;return this.text(a,["id"])||this.text(m,["authorId","author_id","userId","user_id"])||"";}
    authorCtx(m){const a=this.val(m,["author"])||{},id=this.authorId(m),u=this.text(a,["username","name","tag"]),g=this.text(a,["globalName","global_name","displayName","nick"]);let line="";if(g&&u&&g!==u)line=`${g} (@${u})${id?` (<@${id}>)`:""}`;else if(g)line=`${g}${id?` (<@${id}>)`:""}`;else if(u)line=`${u}${id?` (<@${id}>)`:""}`;else if(id)line=`<@${id}>`;return {id,line,key:id?`<@${id}>`:this.authorKey(line)};}
    authorKey(s){const t=clean(s).replace(/\s+/g," ").trim(),id=t.match(/<@!?(\d{14,24})>/)?.[1];if(id)return `<@${id}>`;const lead=t.match(/@([^\s()]+)(?:\s|\(|$)/)?.[1];if(lead)return lead.toLowerCase();const p=t.match(/\((@?[^()]+)\)/)?.[1];return (p||t).replace(/^@/,"").replace(/\s+/g," ").trim().toLowerCase()||"unknown";}
    flatten(m){const parts=[];this.parts(m,parts);return clean(parts.filter(Boolean).join("\n"));}
    parts(src,parts,seen=new Set(),d=0){if(!src||d>6)return;if(typeof src==="string"){parts.push(src);return;}if(Array.isArray(src)||src instanceof Map||src instanceof Set){for(const x of this.arr(src))this.parts(x,parts,seen,d+1);return;}if(typeof src!=="object"||seen.has(src))return;seen.add(src);parts.push(this.text(src,["content","cleanContent","rawContent","text"]));for(const e of this.arr(this.val(src,["embeds","rawEmbeds"]))){parts.push(this.text(e,["title","rawTitle"]),this.text(e,["description","rawDescription"]),this.text(e,["url","rawUrl"]),this.text(this.val(e,["footer","rawFooter"]),["text","rawText"]),this.text(this.val(e,["author","rawAuthor"]),["name","rawName"]));for(const f of this.arr(this.val(e,["fields","rawFields","_fields"]))){const n=this.text(f,["name","rawName"]),v=this.text(f,["value","rawValue"]);if(n||v)parts.push(`${n}: ${v}`);}}for(const a of this.arr(this.val(src,["attachments","rawAttachments"])))parts.push(this.text(a,["url","rawUrl"]),this.text(a,["proxyUrl","proxy_url"]),this.text(a,["filename","name","title","description"]));for(const k of ["messageSnapshots","message_snapshots","messageSnapshot","message_snapshot","snapshots","forwardedMessages","forwarded_messages","forwardedMessage","forwarded_message","message","snapshot","sourceMessage","source_message","referencedMessage","referenced_message","originalMessage","original_message"]){const n=this.val(src,[k]);if(n)this.parts(n,parts,seen,d+1);}}
    fields(m,label,flat){const out=[],want=this.logLabel(label);for(const e of this.arr(this.val(m,["embeds","rawEmbeds"])))for(const f of this.arr(this.val(e,["fields","rawFields","_fields"]))){const n=this.text(f,["name","rawName"]),v=this.text(f,["value","rawValue"]);if(this.logLabel(n)===want&&v)out.push(clean(v).trim());}const plain=clean(flat).replace(/```/g,"").replace(/\*\*/g,"").replace(/`/g,""),esc=String(label).replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),re=new RegExp(`^\\s*(?:[>\\-•]\\s*)?${esc}\\s*[:：]\\s*(.*)$`,"i"),lines=plain.split("\n");for(let i=0;i<lines.length;i++){const mt=lines[i].match(re);if(!mt)continue;const block=[mt[1].trim()].filter(Boolean);for(let j=i+1;j<lines.length;j++){const line=lines[j].trim();if(this.isLabel(line))break;if(line)block.push(line);}out.push(block.join("\n").trim());}return [...new Set(out.filter(Boolean))];}
    firstField(m,labels,flat){for(const l of labels){const v=this.fields(m,l,flat)[0];if(v)return v;}return "";}
    isLabel(line){const t=String(line||"").trim();if(/^https?:\/\//i.test(t))return false;return /^(?:[>\-•]\s*)?[A-Za-z][A-Za-z0-9 _-]{1,44}\s*[:：]/.test(t);}
    logLabel(v){return clean(v).replace(/[>*_`~|]/g,"").replace(/[:：]/g,"").trim().toLowerCase();}
    isEgg(text,vals){return [text].concat(vals).some(v=>{const s=clean(v).toLowerCase(),n=norm(v);return s.includes(String(this.settings.eggChatChannelId))||n.includes("egg chat")||n.includes("eggchat");});}
    shareText(vals,flat){return vals.find(v=>this.link(v))||this.msgBlock(flat)||flat.split("\n").find(l=>this.link(l))?.trim()||"";}
    msgBlock(text){const lines=clean(text).replace(/\*\*/g,"").replace(/`/g,"").split("\n");for(let i=0;i<lines.length;i++){const m=lines[i].match(/^\s*(?:[>\-•]\s*)?Message\s*[:：]\s*(.*)$/i);if(!m)continue;const b=[m[1].trim()].filter(Boolean);for(let j=i+1;j<lines.length;j++){const line=lines[j].trim();if(this.isLabel(line))break;if(line)b.push(line);}const out=b.join("\n").trim();if(this.link(out))return out;}return "";}
    link(v){const t=clean(v);for(const p of SHARE_PATTERNS){p.lastIndex=0;const m=t.match(p);if(!m)continue;const raw=m[1]?.startsWith("/")?`https://www.roblox.com${m[1]}`:m[0];return raw.trim().replace(/[),.]+$/g,"").replace(/&amp;/g,"&");}return "";}
    sourceMessageId(m,flat){return String(this.firstField(m,["Message ID","Message Id","Deleted Message ID","Deleted Message Id"],flat)||"").match(/\d{14,24}/)?.[0]||"";}
    mention(text){return clean(text).match(/@[\w.'-]{2,40}\s*\([^\n]+\)/)?.[0]||clean(text).match(/<@!?\d{14,24}>/)?.[0]||"";}
    val(src,keys){if(!src)return undefined;const c=[src];try{if(typeof src.toJS==="function")c.push(src.toJS());}catch(_){}for(const o of c){if(!o)continue;for(const k of keys){try{const v=o[k];if(v!==undefined&&typeof v!=="function")return v;}catch(_){}try{if(typeof o.get==="function"){const v=o.get(k);if(v!==undefined&&typeof v!=="function")return v;}}catch(_){}}}return undefined;}
    text(src,keys){const v=this.val(src,keys);if(v===undefined||v===null)return "";if(typeof v==="string")return v;if(typeof v==="number"||typeof v==="boolean")return String(v);try{if(typeof v.toString==="function"&&v.toString!==Object.prototype.toString){const t=v.toString();return t==="[object Object]"?"":t;}}catch(_){}return "";}
    arr(v){if(!v)return[];if(Array.isArray(v))return v;if(v instanceof Map||v instanceof Set)return[...v.values()];try{if(typeof v.toArray==="function")return v.toArray();}catch(_){}try{if(typeof v.toJS==="function"){const raw=v.toJS();return Array.isArray(raw)?raw:(raw&&typeof raw==="object"?Object.values(raw):[]);}}catch(_){}return typeof v==="object"?Object.values(v):[];}
    guildId(){return String(location?.pathname||"").match(/\/channels\/(\d+)/)?.[1]||"";}
};
